name: Consistency Check
on: [pull_request]
jobs:
  check:
    name: Check all JSON Files
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maus ahbicht
      - name: Run Consistency Check
        run: |
          python .github/consistency_check.py
